CREATE TABLE [dbo].[Table]
(
	[ID] INT NOT NULL IDENTITY, 
    [GRUPADI] NVARCHAR(30) NULL, 
    [GRUPKODU] NVARCHAR(30) NULL, 
    [SAVEDATE] DATETIME NULL, 
    [SAVEUSER] INT NULL, 
    [EDITDATE] DATETIME NULL, 
    [EDITUSER] INT NULL, 
    CONSTRAINT [PK_Table] PRIMARY KEY ([ID]) 
)
